### PR TITLE
Dev0-2

### LINKED ISSUE #323: Variable is used when it could be nothing
In the code segment below from the function `build!` the check for `isnothing(stage)` should be moved directly below the assignment of `stage`.  The current code will crash if `stage` is nothing.
```
    for (stage_number, stage_name) in sim.sequence.order
        stage = get(sim.stages, stage_name, nothing)
        stage_interval = sim.sequence.intervals[stage_name]
        executions = Int(sim.step_resolution / stage_interval)
        stage.internal = StageInternal(stage_number, executions, 0, nothing)
        isnothing(stage) &&
        throw(IS.ConflictingInputsError("Stage $(stage_name) not found in the stages definitions"))
        PSY.check_forecast_consistency(stage.sys)
        _attach_feed_forward!(sim, stage_name)
    end

```

### LINKED ISSUE #331: initial_time argument in SimulationSequence causes error
```julia
julia> DA_RT_sequence = SimulationSequence(order = order,
                                           horizons = horizons,
                                           intervals = intervals,
                                           intra_stage_chronologies = inter_stage_chronologies,
                                           ini_cond_chronology = ini_cond_chronology,
                                           feed_forward = feed_forward,
                                           cache = cache, initial_time = Dates.DateTime("2020-06-01T00:00:00"))
SimulationSequence()


julia> sim = Simulation(name = "rts-test",
                       steps = 2, step_resolution = Hour(24),
                       stages = stages_definition,
                       stages_sequence = DA_RT_sequence,
                       simulation_folder = file_path)
Simulation()


julia> build!(sim)
[ Info: Building Stage 2-ED
┌ Warning: The data doesn't include devices of type InterruptibleLoad, consider changing the device models
└ @ PowerSimulations ~/.julia/packages/PowerSimulations/Oj26C/src/devices_models/device_constructors/common/constructor_validations.jl:4
[ Info: Building Stage 1-UC
ERROR: ArgumentError: forecast InfrastructureSystems.ForecastKey(InfrastructureSystems.DeterministicInternal, 2020-06-01T00:00:00, "get_requirement") is not stored
Stacktrace:
 [1] get_forecast at /Users/cbarrows/.julia/packages/InfrastructureSystems/wvWoQ/src/forecasts.jl:100 [inlined]
 [2] get_forecast(::Type{InfrastructureSystems.DeterministicInternal}, ::VariableReserve{ReserveDown}, ::DateTime, ::String) at /Users/cbarrows/.julia/packages/InfrastructureSystems/wvWoQ/src/component.jl:114
 [3] get_forecast(::Type{Deterministic}, ::VariableReserve{ReserveDown}, ::DateTime, ::String) at /Users/cbarrows/.julia/packages/InfrastructureSystems/wvWoQ/src/component.jl:62
 [4] get_forecast at /Users/cbarrows/.julia/packages/PowerSystems/juAqn/src/base.jl:723 [inlined]
 [5] service_requirement_constraint!(::PowerSimulations.PSIContainer, ::VariableReserve{ReserveDown}, ::ServiceModel{VariableReserve{ReserveDown},RangeReserve}) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/services_models/reserves.jl:47
 [6] #construct_service!#52(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(PowerSimulations.construct_service!), ::PowerSimulations.PSIContainer, ::InfrastructureSystems.FlattenIteratorWrapper{VariableReserve{ReserveDown}}, ::Dict{NamedTuple{(:type, :name),Tuple{DataType,String}},ServiceContributingDevices}, ::ServiceModel{VariableReserve{ReserveDown},RangeReserve}, ::Dict{Symbol,DeviceModel}) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/services_models/services_constructor.jl:56
 [7] construct_service!(::PowerSimulations.PSIContainer, ::InfrastructureSystems.FlattenIteratorWrapper{VariableReserve{ReserveDown}}, ::Dict{NamedTuple{(:type, :name),Tuple{DataType,String}},ServiceContributingDevices}, ::ServiceModel{VariableReserve{ReserveDown},RangeReserve}, ::Dict{Symbol,DeviceModel}) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/services_models/services_constructor.jl:34
 [8] #construct_services!#51(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(PowerSimulations.construct_services!), ::PowerSimulations.PSIContainer, ::System, ::Dict{Symbol,ServiceModel}, ::Dict{Symbol,DeviceModel}) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/services_models/services_constructor.jl:13
 [9] construct_services! at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/services_models/services_constructor.jl:8 [inlined]
 [10] #_build!#27(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(PowerSimulations._build!), ::PowerSimulations.PSIContainer, ::OperationsProblemTemplate, ::System) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/core/operations_problem.jl:444
 [11] _build! at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/core/operations_problem.jl:440 [inlined]
 [12] #_build_stages!#39(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(PowerSimulations._build_stages!), ::Simulation) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/core/simulation.jl:272
 [13] _build_stages! at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/core/simulation.jl:259 [inlined]
 [14] #build!#41(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(build!), ::Simulation) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/core/simulation.jl:339
 [15] build!(::Simulation) at /Users/cbarrows/.julia/packages/PowerSimulations/Oj26C/src/core/simulation.jl:321
 [16] top-level scope at REPL[147]:1
```

### PR DESCRIPTION
**Pull request by jd-lara**
The PR is ready for review. If there aren't any major objections, we could go forward with a new tag. 

Closes #331 
Closes #323

### CODE REVIEW

File: src/templates/operations_problem_templates.jl [hunk 1]
```diff
@@ -0,0 +1,208 @@
...
+- `network::Type{<:PM.AbstractPowerModel}` : override default network model settings
+- `devices::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `branches::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `services::Dict{Symbol, ServiceModel}` : override default `ServiceModel` settings
+- `optimizer::JuMP Optimizer` : An optimizer is a required key word
+"""
+
+function run_unit_commitment(sys::PSY.System; kwargs...)
+    template = PSI.template_unit_commitment(; kwargs...)
+    op_problem = OperationsProblem(UnitCommitmentProblem, template, sys)
```
Comment (claytonpbarrows) [inline src/templates/operations_problem_templates.jl]: this line needs a `kwargs...`

File: src/templates/operations_problem_templates.jl [hunk 2]
```diff
@@ -0,0 +1,208 @@
...
+
+Creates an `OperationsProblemTemplate` with default DeviceModels for a Unit Commitment
+problem. Uses the template to create an `OperationsProblem`. Solves the created operations problem.
+
+# Example
+```julia
+results = run_unit_commitment(system; optimizer = optimizer)
+```
+
+# Accepted Key Words
```
Comment (claytonpbarrows) [inline src/templates/operations_problem_templates.jl]: This is incomplete. We need to be able to pass the kwargs for the `OperationsProblem` constructor here too

File: src/templates/operations_problem_templates.jl [hunk 3]
```diff
@@ -0,0 +1,208 @@
...
+- `network::Type{<:PM.AbstractPowerModel}` : override default network model settings
+- `devices::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `branches::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `services::Dict{Symbol, ServiceModel}` : override default `ServiceModel` settings
+- `optimizer::JuMP Optimizer` : An optimizer is a required key word
+"""
+
+function run_unit_commitment(sys::PSY.System; kwargs...)
+    template = PSI.template_unit_commitment(; kwargs...)
```
Comment (claytonpbarrows) [inline src/templates/operations_problem_templates.jl]: can we use the function defined on line 152 here to make maintenance easier?

File: src/templates/operations_problem_templates.jl [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+- `network::Type{<:PM.AbstractPowerModel}` : override default network model settings
+- `devices::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `branches::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `services::Dict{Symbol, ServiceModel}` : override default `ServiceModel` settings
+- `optimizer::JuMP optimizer` : a JuMP optimizer is a required key word
+"""
+
+function run_economic_dispatch(sys::PSY.System; kwargs...)
+    template = PSI.template_economic_dispatch(; kwargs...)
+    op_problem = OperationsProblem(EconomicDispatchProblem, template, sys)
```
Comment (claytonpbarrows) [inline src/templates/operations_problem_templates.jl]: add kwargs

File: src/templates/operations_problem_templates.jl [hunk 5]
```diff
@@ -0,0 +1,208 @@
...
+# Accepted Key Words
+- `network::Type{<:PM.AbstractPowerModel}` : override default network model settings
+- `devices::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `branches::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `services::Dict{Symbol, ServiceModel}` : override default `ServiceModel` settings
+"""
+
+function UnitCommitmentProblem(system::PSY.System; kwargs...)
+    template = template_unit_commitment(; kwargs...)
+    op_problem = OperationsProblem(UnitCommitmentProblem, template, system)
```
Comment (claytonpbarrows) [inline src/templates/operations_problem_templates.jl]: add kwargs

File: src/templates/operations_problem_templates.jl [hunk 6]
```diff
@@ -0,0 +1,208 @@
...
+# Accepted Key Words
+- `network::Type{<:PM.AbstractPowerModel}` : override default network model settings
+- `devices::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `branches::Dict{Symbol, DeviceModel}` : override default `DeviceModel` settings
+- `services::Dict{Symbol, ServiceModel}` : override default `ServiceModel` settings
+"""
+
+function EconomicDispatchProblem(system::PSY.System; kwargs...)
+    template = template_economic_dispatch(; kwargs...)
+    op_problem = OperationsProblem(EconomicDispatchProblem, template, system)
```
Comment (claytonpbarrows) [inline src/templates/operations_problem_templates.jl]: add kwargs

File: src/templates/operations_problem_templates.jl [hunk 7]
```diff
@@ -0,0 +1,208 @@
...
+struct UnitCommitmentProblem <: AbstractOperationsProblem end
+
+function _generic_template(; kwargs...)
+    network = get(kwargs, :network, CopperPlatePowerModel)
+
+    devices = get(
+        kwargs,
+        :devices,
+        Dict(
+            :Generators => DeviceModel(PSY.ThermalStandard, ThermalBasicUnitCommitment),
```
Comment (claytonpbarrows) [inline src/templates/operations_problem_templates.jl]: Should this be `ThermalStandardUnitCommitment`?

File: test/test_simulation_build.jl [hunk 8]
```diff
@@ -0,0 +1,339 @@
...
+
+    @testset "Simulation with provided initial time" begin
+        second_day = DayAhead[24] + Hour(1)
+        sim = Simulation(
+            name = "test",
+            steps = 1,
+            stages = stages_definition,
+            stages_sequence = sequence,
+            simulation_folder = file_path,
+            initial_time = second_day,
```
Comment (claytonpbarrows) [inline test/test_simulation_build.jl]: This test does not catch the condition where a system has a single long forecast.  The RTS errors:
```julia
julia> sim = Simulation(
           name = "aggregation",
           steps = 2,
           stages = stages_definition,
           stages_sequence = sequence,
           simulation_folder = file_path,
           initial_time = Dates.DateTime("2020-01-05T00:00:00")
           )
Simulation()


julia> build!(sim)
┌ Debug: (3600000 milliseconds, 3600000 milliseconds)
└ @ PowerSimulations ~/Documents/repos/PowerSimulations.jl/src/core/feedforward.jl:38
[ Info: Building Stage 2-ED
┌ Debug: Instantiating the JuMP model
└ @ PowerSimulations ~/Documents/repos/PowerSimulations.jl/src/core/psi_container.jl:18
┌ Debug: Building HydroDispatch with HydroDispatchRunOfRiver formulation
└ @ PowerSimulations ~/Documents/repos/PowerSimulations.jl/src/core/operations_problem.jl:452
┌ Debug: assign_variable
│   name = :P_HydroDispatch
└ @ PowerSimulations ~/Documents/repos/PowerSimulations.jl/src/core/psi_container.jl:331
┌ Debug: 2020-01-05T00:00:00
└ @ PowerSimulations ~/Documents/repos/PowerSimulations.jl/src/devices_models/devices/hydro_generation.jl:176
ERROR: ArgumentError: forecast InfrastructureSystems.ForecastKey(InfrastructureSystems.DeterministicInternal, 2020-01-05T00:00:00, "get_rating") is not stored
Stacktrace
```

File: PowerSimulationsPlots/src/fuel_results.jl [hunk 9]
```diff
@@ -0,0 +1,211 @@
...
+    "Gas_CC",
+    "Gas_CT",
+    "Storage",
+    "Oil_ST",
+    "Oil_CT",
+    "Sync_Cond",
+    "Wind",
+    "Solar",
+    "CSP",
+    "curtailment",
```
Comment (kdheepak) [inline PowerSimulationsPlots/src/fuel_results.jl]: Why is `"curtailment"` alone lower case `c`?

File: PowerSimulationsPlots/src/plot_recipes.jl [hunk 10]
```diff
@@ -0,0 +1,670 @@
+### PlotlyJS set up
+import PlotlyJS
+import WebIO
+WebIO.install_jupyter_nbextension()
```
Comment (kdheepak) [inline PowerSimulationsPlots/src/plot_recipes.jl]: Why is this is the global scope?

File: src/core/simulation.jl [hunk 11]
```diff
@@ -0,0 +1,572 @@
...
+            stage.internal = StageInternal(stage_number, executions, 0, nothing)
+            _attach_feedforward!(sim, stage_name)
+        end
+        _assign_feedforward_chronologies(sim)
+        _check_steps(sim, stage_initial_times)
+        _build_stages!(sim; kwargs...)
+        sim.internal.compiled_status = true
+    end
+    # TODO: Send to logging
+    TimerOutputs.print_timer(BUILD_SIMULATION_TIMER)
```
Comment (jd-lara) [inline src/core/simulation.jl]: @daniel-thom here is the printout of timer outputs.

File: Project.toml [hunk 12]
```diff
@@ -4,50 +4,37 @@ authors = ["Jose Daniel Lara", "Dheepak Krishnamurthy", "Clayton Barrows"]
...
 MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
 ParameterJuMP = "774612a8-9878-5177-865a-ca53ae2495f9"
 Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
 PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
 PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
-RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
 Requires = "ae029012-a4dd-5104-9daa-d747884805df"
+SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
 TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
+TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
```
Comment (kdheepak) [inline Project.toml]: I don't think we need `JuliaFormatter` and `TimerOutputs` in this `Project.toml`. You can install them in your global environment if you'd like to use them when working on PowerSimulations.jl.

Comment (jd-lara) [reply Project.toml]: This is true for JuliaFormatter, not for TimerOutputs.

File: test/test_simulation_build.jl (hunk 8 above)
Comment (jd-lara) [reply test/test_simulation_build.jl]: @claytonpbarrows this is resolved via 
55a4799

File: src/core/cache.jl [hunk 13]
```diff
@@ -0,0 +1,25 @@
...
+
+"""
+Tracks the last time status of a device changed in a simulation
+"""
+# The current implementation will require all custom caches to have the same data template
+mutable struct TimeStatusChange <: AbstractCache
+    device_type::Type{<:PSY.Device}
+    value::JuMP.Containers.DenseAxisArray{Dict{Symbol, Float64}}
+    ref::UpdateRef
+end
```
Comment (kdheepak) [inline src/core/cache.jl]: The docstring for `TimeStatusChange` will not show up.

Screen Shot 2020-02-19 at 1 45 40 PM

File: src/core/abstract_types.jl [hunk 14]
```diff
@@ -0,0 +1,10 @@
+# All subtypes of AbstractAffectFeedForward must define the field affected_variables.
+# TODO: make a unit test that checks for this.
+abstract type AbstractAffectFeedForward end
+
+abstract type AbstractCache end
+abstract type FeedForwardChronology end
+abstract type IniCondChronology end
```
Comment (kdheepak) [inline src/core/abstract_types.jl]: What does `IniCondChronology` stand for? `InitialConditionChronology`? Everything else is spelled out and I would prefer this to be too.

File: src/core/definitions.jl [hunk 15]
```diff
@@ -13,15 +13,93 @@ const IS = InfrastructureSystems
...
-const JuMPAffineExpressionArray = Matrix{GAE{V}} where V<:JuMP.AbstractVariableRef
-const JuMPAffineExpressionVector = Vector{GAE{V}} where V<:JuMP.AbstractVariableRef
+const PGAE{V} =
+    PJ.ParametrizedGenericAffExpr{Float64, V} where {V <: JuMP.AbstractVariableRef}
+const GAE{V} = JuMP.GenericAffExpr{Float64, V} where {V <: JuMP.AbstractVariableRef}
+const JuMPAffineExpressionArray = Matrix{GAE{V}} where {V <: JuMP.AbstractVariableRef}
+const JuMPAffineExpressionVector = Vector{GAE{V}} where {V <: JuMP.AbstractVariableRef}
 const JuMPConstraintArray = JuMP.Containers.DenseAxisArray{JuMP.ConstraintRef}
 const JuMPParamArray = JuMP.Containers.DenseAxisArray{PJ.ParameterRef}
 const DSDA = Dict{Symbol, JuMP.Containers.DenseAxisArray}
```
Comment (kdheepak) [inline src/core/definitions.jl]: This can be renamed to: 

```
const DenseAxisArrayContainer = Dict{Symbol, JuMP.Containers.DenseAxisArray}
```

for consistency.

File: src/core/definitions.jl [hunk 16]
```diff
@@ -13,15 +13,93 @@ const IS = InfrastructureSystems
...
+
+# Tolerance of comparisons
+const ComparisonTolerance = 1.0e-10
```
Comment (kdheepak) [inline src/core/definitions.jl]: Two comments here:

1) This is a value and a constant. Convention in the code base is to use ALL_CAPS.
2) There are two types of tolerances that can be set for comparison, absolute and relative tolerance, and we tend to be using absolute tolerance.

I would rename this to the following: 

```julia
const ABSOLUTE_TOLERANCE = 1e-10
```

File: PowerSimulationsPlots/src/report_design/report_design.jmd [hunk 17]
```diff
@@ -1,18 +1,23 @@
 ---
 title : Weave example
 author : SIIP
-date : Friday the 13th
+date : 1-14
```
Comment (kdheepak) [inline PowerSimulationsPlots/src/report_design/report_design.jmd]: Can we use `YYYY-MM-DD` for the format of dates everywhere?

File: src/PowerSimulations.jl [hunk 18]
```diff
@@ -153,26 +163,29 @@ JuMP.Model(optimizer::Nothing; kwargs...) = JuMP.Model(kwargs...)
 ################################################################################
```
Comment (kdheepak) [inline src/PowerSimulations.jl]: I'm not sure why a user would ever want to pass an optimizer as nothing. Can you clarify why this is needed by adding a comment about why this is being done?

Also, move 

```julia
JuMP.Model(optimizer::Nothing; kwargs...) = JuMP.Model(kwargs...)
```

to the end of the file when adding a comment about why this method overloading is required.

File: src/routines/write_results.jl [hunk 19]
```diff
@@ -40,184 +48,239 @@ function _write_data(data::DataFrames.DataFrame, save_path::AbstractString, file
...
+    _write_data(res.variables, res.time_stamp, folder_path; kwargs...)
+    _write_optimizer_log(res.optimizer_log, folder_path)
+    _write_data(res.time_stamp, folder_path, "time_stamp"; kwargs...)
+    files = collect(readdir(folder_path))
+    compute_file_hash(folder_path, files)
+    @info("Files written to $folder_path folder.")
+    return
+end
+
+function compute_file_hash(path::String, files::Array)
```
Comment (kdheepak) [inline src/routines/write_results.jl]:
```julia
function compute_file_hash(path::String, files::Vector{String})
```

Comment (kdheepak) [reply src/routines/write_results.jl]: Also, the `compute_file_hash` function can be moved to `src/utils/utils.jl`.

File: PowerSimulationsPlots/src/report_design/report_design.jmd (hunk 17 above)
Comment (Lilyhanig) [reply PowerSimulationsPlots/src/report_design/report_design.jmd]: @kdheepak this is a report template for the user to change, so the date added was somewhat arbitrary

File: src/routines/write_results.jl (hunk 19 above)
Comment (jd-lara) [reply src/routines/write_results.jl]: File re-organization needs to be done later.

File: PowerSimulationsPlots/src/report_design/report_design.jmd (hunk 17 above)
Comment (jd-lara) [reply PowerSimulationsPlots/src/report_design/report_design.jmd]: Moved to another repo.

File: PowerSimulationsPlots/src/fuel_results.jl (hunk 9 above)
Comment (jd-lara) [reply PowerSimulationsPlots/src/fuel_results.jl]: This was moved to other repo

File: PowerSimulationsPlots/src/plot_recipes.jl (hunk 10 above)
Comment (jd-lara) [reply PowerSimulationsPlots/src/plot_recipes.jl]: This is moved to another repo

File: src/core/simulation.jl [hunk 20]
```diff
@@ -0,0 +1,569 @@
...
+        field_dict = getfield(stage.template, key[2])
+        device_model = get(field_dict, key[3], nothing)
+        isnothing(device_model) &&
+        throw(IS.ConflictingInputsError("Device model $(key[3]) not found in stage $(stage_name)"))
+        device_model.feedforward = ff
+    end
+    return
+end
+
+function _check_steps(
```
Comment (claytonpbarrows) [inline src/core/simulation.jl]: add a check to make sure that SimulationSequence.step_resolution is not longer than the first stage interval. 
The following error is hard to understand:
```
julia> sequence = SimulationSequence(
           step_resolution = Hour(24),
           order = Dict(1 => "UC", 2 => "ED"),
           feedforward_chronologies = Dict(("UC" => "ED") => Synchronize(periods = 12)),
           horizons = Dict("UC" => 18, "ED" => 12),
           intervals = Dict(
               "UC" => (Hour(12), Consecutive()),
                       "ED" => (Hour(1), Consecutive()),
           ),
           feedforward = Dict(
               ("ED", :devices, :Generators) => SemiContinuousFF(
                   binary_from_stage = PSI.ON,
                   affected_variables = [PSI.ACTIVE_POWER],
               ),
           ),
           cache = Dict("UC" => [TimeStatusChange(PSY.ThermalStandard, PSI.ON)]),
           ini_cond_chronology = InterStageChronology(),
       )
Feed Forward Chronology
-----------------------

ED: SemiContinuousFF -> Generators

                     UC--┐ from : On
                         |
┌----┬----┬----┬----┬----┼----┬----┬----┬----┬----┬----┐
|    |    |    |    |    |    |    |    |    |    |    |
|    |    |    |    |    |    |    |    |    |    |    |
└─ED └─ED └─ED └─ED └─ED └─ED └─ED └─ED └─ED └─ED └─ED └─ED (12) to : ["P"]

Initial Condition Chronology
----------------------------

1
|
|
2 --> 2 ... (x12)   


julia> 

julia> f = joinpath(rts_siip_dir,"test_rts")
"/var/folders/27/2jr8c7gn4j72fvrg4qt81zrw8w_711/T/RTS-GMLC-master/RTS_Data/FormattedData/SIIP/test_rts"

julia> file_path = ispath(f) ? f : mkdir(f)
"/var/folders/27/2jr8c7gn4j72fvrg4qt81zrw8w_711/T/RTS-GMLC-master/RTS_Data/FormattedData/SIIP/test_rts"

julia> sim = Simulation(
           name = "aggregation",
           steps = 1,
           stages = stages_definition,
           stages_sequence = sequence,
           simulation_folder = file_path,
           #initial_time = Dates.DateTime("2020-06-05T00:00:00")
           )
Simulation()


julia> build!(sim)
ERROR: AssertionError: length(findall((x->begin
                    #= /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation.jl:278 =#
                    x == stage_number
                end), sim.sequence.execution_order)) == execution_counts
Stacktrace:
 [1] _check_steps(::Simulation, ::Dict{Int64,Array{DateTime,1}}) at /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation.jl:278
 [2] macro expansion at /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation.jl:384 [inlined]
 [3] macro expansion at /Users/cbarrows/.julia/packages/TimerOutputs/7Id5J/src/TimerOutput.jl:214 [inlined]
 [4] #build!#320(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(build!), ::Simulation) at /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation.jl:363
 [5] build!(::Simulation) at /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation.jl:362
 [6] top-level scope at REPL[12]:1
```

Comment (jd-lara) [reply src/core/simulation.jl]: fixed via 3ee2f88

File: src/core/simulation_sequence.jl [hunk 21]
```diff
@@ -134,6 +134,14 @@ function _check_chronology_consistency(
     #TODO: Add more consistency checks
     return
 end
+
+function _check_step_interval_consistency(step_resolution::Dates.TimePeriod, first_stage_interval::Dates.TimePeriod)
+    if step_resolution != first_stage_interval
+        throw(IS.ConflictingInputsError("Currently specifing a step resolution not equal to the first stage interval is not supported"))
```
Comment (claytonpbarrows) [inline src/core/simulation_sequence.jl]: "step_resolution != first_stage_interval : this specification is not currently supported, adjust step_resolution or intervals arguments."

FWIW, I still think we should drop `step_resolution`

File: src/core/simulation_sequence.jl [hunk 22]
```diff
@@ -176,6 +184,7 @@ mutable struct SimulationSequence
             _intervals[k] = (IS.time_period_conversion(intervals[k][1]), intervals[k][2])
         end
         step_resolution = IS.time_period_conversion(step_resolution)
+        _check_step_interval_consistency(step_resolution, get_stage_interval(order[1]))
```
Comment (claytonpbarrows) [inline src/core/simulation_sequence.jl]: This introduced an error:
```julia
ERROR: LoadError: MethodError: no method matching get_stage_interval(::String)
Closest candidates are:
  get_stage_interval(::Simulation, ::String) at /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation.jl:102
  get_stage_interval(::SimulationSequence, ::String) at /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation_sequence.jl:213
Stacktrace:
 [1] (::PowerSimulations.var"#SimulationSequence#35#36")(::Dict{String,Int64}, ::Hour, ::Dict{String,Tuple{Hour,Consecutive}}, ::Dict{Int64,String}, ::Dict{Pair{String,String},Synchronize}, ::Dict{Tuple{String,Symbol,Symbol},SemiContinuousFF}, ::InterStageChronology, ::Dict{String,Array{TimeStatusChange,1}}, ::Type{SimulationSequence}) at /Users/cbarrows/Documents/repos/PowerSimulations.jl/src/core/simulation_sequence.jl:190
 [2] (::Core.var"#kw#Type")(::NamedTuple{(:step_resolution, :order, :feedforward_chronologies, :horizons, :intervals, :feedforward, :cache, :ini_cond_chronology),Tuple{Hour,Dict{Int64,String},Dict{Pair{String,String},Synchronize},Dict{String,Int64},Dict{String,Tuple{Hour,Consecutive}},Dict{Tuple{String,Symbol,Symbol},SemiContinuousFF},Dict{String,Array{TimeStatusChange,1}},InterStageChronology}}, ::Type{SimulationSequence}) at ./none:0
 [3] top-level scope at /Users/cbarrows/Documents/repos/PowerSimulations.jl/rts_simulation.jl:84
 [4] include at ./boot.jl:328 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1105
 [6] include(::Module, ::String) at ./Base.jl:31
 [7] include(::String) at ./client.jl:424
 [8] top-level scope at REPL[7]:1
```

**Comment by kdheepak** [comment]
These appear to be the only two files that have upper case letters in the name of the files.

```
│  │  └── devices
│  │     ├── AC_branches.jl
│  │     ├── DC_branches.jl
```

File: src/utils/simulation_results.jl [hunk 23]
```diff
@@ -0,0 +1,210 @@
...
+            var = Feather.read(file_path)
+            variables[(variable[l])] = vcat(variables[(variable[l])], var[1:time_length, :])
+            if l == 1
+                time_stamp = vcat(time_stamp, _read_time(file_path, time_length))
+                check_file_integrity(dirname(file_path))
+            end
+        end
+    end
+    time_stamp[!, :Range] = convert(Array{Dates.DateTime}, time_stamp[!, :Range])
+    @show references[stage][variable[1]][1, :File_Path]
```
Comment (claytonpbarrows) [inline src/utils/simulation_results.jl]: This is failing. I'm not quite sure why, but the df in `references[stage][variable[1]]`  is empty. @Lilyhanig

File: src/utils/simulation_results.jl [hunk 24]
```diff
@@ -0,0 +1,210 @@
...
+stage = 2
+step = ["step-1", "step-2", "step-3"] # has to match the date range
+variable = [:P_ThermalStandard, :P_RenewableDispatch]
+results = load_simulation_results(stage, step, variable, SimulationResultsReference)
+```
+# Accepted Key Words
+- `write::Bool`: if true, the aggregated results get written back to the results file in the folder structure
+"""
+
+function load_simulation_results(
```
Comment (claytonpbarrows) [inline src/utils/simulation_results.jl]: @Lilyhanig can we add a function to load simulation results from file?

Comment (Lilyhanig) [reply src/utils/simulation_results.jl]: That's load_operation_results() I could change that function name to be just load_results() so it's more clear what to do if you have aggregated results already..... @claytonpbarrows @jd-lara thoughts? I'm working on the how-to's for this now.

**Comment by kdheepak** [comment]
Everything that I've seen so far looks good. I think there's still some known refactoring that is to come to simplify "state" while PowerSimulations.jl is running and to decrease some of the complexity, but overall it is looking good. I'm excited for all the features this will add. 

Going forward, it would be nice to maintain a `HISTORY.md`, `NEWS.md` or `CHANGELOG.md`, file in the root of the repository that lists all the changes between releases (see examples [here](https://github.com/JuliaLang/julia/blob/master/HISTORY.md), [here](https://github.com/JuliaOpt/JuMP.jl/blob/master/NEWS.md) and [here](https://github.com/lanl-ansi/PowerModels.jl/blob/master/CHANGELOG.md)) so it is easier for people who want to get involved to know what new features have been added.

**Comment by kdheepak** [comment]
I recommend doing a squash and merge for this PR.

File: src/utils/simulation_results.jl (hunk 24 above)
Comment (jd-lara) [reply src/utils/simulation_results.jl]: fixed via  7b8ae54
