### PR TITLE
Fix pm integration

### LINKED ISSUE #186: fix rating constraint
currently is P+Q<=S^2
should be P^2+Q^2<=S^2

### PR DESCRIPTION
**Pull request by claytonpbarrows**
- closes #186 
- will address #185 and #174

### CODE REVIEW

File: src/devices/device_models/common/rating_constraints.jl [hunk 1]
```diff
@@ -36,7 +36,7 @@ function norm_two_constraint(ps_m::CanonicalModel,
 
     for r in rating_data
         for t in time_steps
-          constraint[r[1], t] = JuMP.@constraint(ps_m.JuMPmodel, var1[r[1], t] + var2[r[1], t] <= r[2].max^2)
+          constraint[r[1], t] = JuMP.@constraint(ps_m.JuMPmodel, var1[r[1], t]^2 + var2[r[1], t]^2 <= r[2].max^2)
```
Comment (jd-lara) [inline src/devices/device_models/common/rating_constraints.jl]: There is something odd in this implementation probably from before. 
1. It shouldn't be called the norm_two_constraint since it doesn't use the two norm formulation. It is a quadratic form. 
2. The rating data should be only `Vector{Tuple{String, Float}}` I think we call it `NamedTuple` and the constraint should be 
```
 JuMP.@constraint(ps_m.JuMPmodel, var1[r[1], t]^2 + var2[r[1], t]^2 <= r[2]^2
```

File: src/network/network_models/powermodels_interface.jl [hunk 2]
```diff
@@ -294,24 +294,35 @@ end
 
 #### PM accessor functions ########
 
+function PMvarmap(system_formulation::Type{S}) where {S <: PM.DCPlosslessForm}
+    pm_var_map = Dict{Type,Dict{Symbol, Union{Symbol,NamedTuple}}}()
+
+    pm_var_map[PSY.Bus] = Dict(:va => :theta)
+    pm_var_map[PSY.ACBranch] = Dict(:p => (from_to = :Pbr_fwd, to_from = nothing))
+    pm_var_map[PSY.DCBranch] = Dict(:p_dc => (from_to = :Pbr_fwd, to_from = nothing))
```
Comment (jd-lara) [inline src/network/network_models/powermodels_interface.jl]: We should discriminate between DC and AC branches.

File: src/network/network_models/powermodels_interface.jl [hunk 3]
```diff
@@ -325,44 +336,40 @@ function add_pm_var_refs!(ps_m::CanonicalModel, system_formulation::Type{S}, sys
...
     
     for (pm_v, ps_v) in pm_var_map[PSY.Bus]
-        if pm_v in keys(ps_m.pm_model.var[:nw][1][:cnd][1])
+        if pm_v in keys(pm_vars)
             ps_m.variables[ps_v] = PSI._container_spec(ps_m.JuMPmodel,
                                                         (PSY.get_name(b) for b in values(bus_dict)),
                                                         time_steps)
             for t in time_steps, (pm_bus, bus) in bus_dict
-                ps_m.variables[ps_v][PSY.get_name(bus), t] = ps_m.pm_model.var[:nw][1][:cnd][1][pm_v][pm_bus]
+                ps_m.variables[ps_v][PSY.get_name(bus), t] = pm_vars[pm_v][pm_bus]
```
Comment (jd-lara) [inline src/network/network_models/powermodels_interface.jl]: same here, get bus name outside

File: src/network/network_models/powermodels_interface.jl [hunk 4]
```diff
@@ -294,24 +294,35 @@ end
...
+    pm_var_map = Dict{Type,Dict{Symbol, Union{Symbol,NamedTuple}}}()
 
     pm_var_map[PSY.Bus] = Dict(:va => :theta,
                                 :vm => :Vm)
-    pm_var_map[PSY.ACBranch] = Dict(:p => :Fbr,
-                                    :q => :Qbr)
-    pm_var_map[PSY.DCBranch] = Dict(:p_dc => :Fp)
+    pm_var_map[PSY.ACBranch] = Dict(:p => (from_to = :Pbr_fwd, to_from = :Pbr_bwd),
+                                    :q => (from_to = :Qbr_fwd, to_from = :Qbr_bwd))
+    pm_var_map[PSY.DCBranch] = Dict(:p_dc => (from_to = :Pbr_fwd, to_from = :Pbr_bwd),
```
Comment (jd-lara) [inline src/network/network_models/powermodels_interface.jl]: Same here, discriminate by DC

File: src/network/network_models/powermodels_interface.jl (hunk 2 above)
Comment (claytonpbarrows) [reply src/network/network_models/powermodels_interface.jl]: These get concatenated with the branch type so it will end up being `:Pbr_fwd_HVDCLine` or `:Pbr_fwd_Line`. I think that further AC/DC distinction isn't needed.

File: src/devices/device_models/AC_branches.jl [hunk 5]
```diff
@@ -118,14 +116,14 @@ function branch_rate_constraint(ps_m::CanonicalModel,
                                         D <: AbstractBranchFormulation,
                                         S <: PM.AbstractPowerFormulation}
 
-    range_data = [(PSY.get_name(h), (min = -1*PSY.get_rate(h), max = PSY.get_rate(h))) for h in devices]
+    @show range_data = [(PSY.get_name(h), PSY.get_rate(h)) for h in devices]
```
Comment (jd-lara) [inline src/devices/device_models/AC_branches.jl]: There is a @show leftover here.

File: src/devices/device_models/AC_branches.jl [hunk 6]
```diff
@@ -51,9 +51,8 @@ end
 function branch_rate_constraint(ps_m::CanonicalModel,
```
Comment (jd-lara) [inline src/devices/device_models/AC_branches.jl]: Branch_rate_constraint is the same for `DCPlossless` and `StandardPTDF` why not use a `Union` and reduce code repetition.

File: src/devices/device_models/common/rating_constraints.jl [hunk 7]
```diff
@@ -1,31 +1,31 @@
...
 
-``` var1[r[1], t] + var2[r[1], t] <= r[2].max^2 ```
+``` var1[r[1], t] + var2[r[1], t] <= r[2]^2 ```
 
 where r in rating data and t in time steps.
 
 # LaTeX
 
-`` x_1 + x_2 \leq r_{max}^2 ``
+`` x_1 + x_2 \leq r^2 ``
```
Comment (jd-lara) [inline src/devices/device_models/common/rating_constraints.jl]: the `^2` are missing here

File: src/devices/device_models/common/rating_constraints.jl [hunk 8]
```diff
@@ -1,31 +1,31 @@
...
+                            rating_data::Vector{Tuple{String, Float64}},
                             cons_name::Symbol,
                             var_names::Tuple{Symbol, Symbol})
 
 Constructs constraint from rating data and related variable tuple.
 
 # Constraint
 
-``` var1[r[1], t] + var2[r[1], t] <= r[2].max^2 ```
+``` var1[r[1], t] + var2[r[1], t] <= r[2]^2 ```
```
Comment (jd-lara) [inline src/devices/device_models/common/rating_constraints.jl]: var1 and var2 are not squared.

File: src/devices/device_models/common/rating_constraints.jl [hunk 9]
```diff
@@ -1,31 +1,31 @@
...
 
 # LaTeX
 
-`` x_1 + x_2 \leq r_{max}^2 ``
+`` x_1 + x_2 \leq r^2 ``
 
 # Arguments
 * ps_m::CanonicalModel : the canonical model built in PowerSimulations
-* rating_data::Vector{NamedMinMax} : rating data name (1) and min/max (2)
+* rating_data::Vector{NamedMinMax} : rating data name (1) and value (2)
```
Comment (jd-lara) [inline src/devices/device_models/common/rating_constraints.jl]: Update Docstring, this is no longer a Vector or NamedMinMax

**Comment by jd-lara** [comment]
The tests are showing that the models are infeasible. This PR needs some more debugging.

**Comment by claytonpbarrows** [comment]
> The tests are showing that the models are infeasible. This PR needs some more debugging.

Something about [this merge](https://github.com/NREL/PowerSimulations.jl/commit/028516d05c2867f4b1a8d70bb3c72655cc3a5460) broke the models. 
They are all broken in the jd/sim_update branch... I don't think that it was something that I did.

**Comment by jd-lara** [comment]
> > The tests are showing that the models are infeasible. This PR needs some more debugging.
> 
> Something about [this merge](https://github.com/NREL/PowerSimulations.jl/commit/028516d05c2867f4b1a8d70bb3c72655cc3a5460) broke the models.
> They are all broken in the jd/sim_update branch... I don't think that it was something that I did.

This issue has been addressed in 1d91d46

File: src/devices/device_models/AC_branches.jl [hunk 10]
```diff
@@ -33,14 +37,14 @@ function flow_variables(ps_m::CanonicalModel,
...
+    var_name = Symbol("Fp_$(B)")
 
     add_variable(ps_m,
                 devices,
                 var_name,
-                false,
-                ub_value = d -> PSY.get_rate(d),
-                lb_value = d -> -1.0*PSY.get_rate(d))
+                false)
+                #ub_value = d -> PSY.get_rate(d), # Add flow bounds in rate constraints
```
Comment (jd-lara) [inline src/devices/device_models/AC_branches.jl]: we should keep the bounds always, PM style. We can make tests to see if they hurt or not.

File: src/devices/device_models/AC_branches.jl [hunk 11]
```diff
@@ -120,14 +108,69 @@ function branch_rate_constraint(ps_m::CanonicalModel,
...
+
+    # This code is intended to do nothing
+
+    return
+
+end
+
+
+function branch_flow_constraint(ps_m::CanonicalModel,
+                                devices::PSY.FlattenIteratorWrapper{PSY.MonitoredLine}, # TODO: Do we need an AbstractMonitoredLine?
```
Comment (jd-lara) [inline src/devices/device_models/AC_branches.jl]: No we don't really need more abstraction here.

File: src/devices/device_models/AC_branches.jl [hunk 12]
```diff
@@ -120,14 +108,69 @@ function branch_rate_constraint(ps_m::CanonicalModel,
...
+    return
+
+end
+
+function branch_flow_constraint(ps_m::CanonicalModel,
+                                devices::PSY.FlattenIteratorWrapper{PSY.MonitoredLine},
+                                device_formulation::Type{FlowMonitoredLine},
+                                system_formulation::Type{S}) where {S <: PM.AbstractPowerFormulation}
+
+    FTflow_range_data = [(PSY.get_name(h), PSY.get_flowlimits(h)) for h in devices]
```
Comment (jd-lara) [inline src/devices/device_models/AC_branches.jl]: Why are these different?

File: src/devices/device_models/DC_branches.jl [hunk 13]
```diff
@@ -51,11 +51,13 @@ end
 
 function branch_rate_constraint(ps_m::CanonicalModel,
                                 devices::PSY.FlattenIteratorWrapper{B},
-                                device_formulation::Type{HVDCLossless},
-                                system_formulation::Type{PM.DCPlosslessForm}) where {B <: PSY.DCBranch}
+                                device_formulation::Type{D},
+                                system_formulation::Type{S}) where {B <: PSY.DCBranch,
+                                                                    D <: AbstractDCLineForm,
+                                                                    S <: PM.DCPlosslessForm}
```
Comment (jd-lara) [inline src/devices/device_models/DC_branches.jl]: Why changed from `system_formulation::Type{PM.DCPlosslessForm}` back to the abstract `S <: PM.DCPlosslessForm`? It should be `AbstractActivePower`?

File: src/devices/device_models/DC_branches.jl [hunk 14]
```diff
@@ -104,14 +106,14 @@ function branch_rate_constraint(ps_m::CanonicalModel,
 
 end
 
-
+#= this one is not needed due to the one starting on line 52
```
Comment (jd-lara) [inline src/devices/device_models/DC_branches.jl]: I don't get this, if it is redundant we can eliminate the code

File: src/network/network_models/networks.jl [hunk 15]
```diff
@@ -23,7 +23,7 @@ export
     QCWRPowerModel, QCWRForm,
     SOCWRConicPowerModel, SOCWRConicForm,
     QCWRTriPowerModel, QCWRTriForm,
-    SOCBFPowerModel, SOCBFForm,
+    SOCBFpowerModel, SOCBFForm,
```
Comment (jd-lara) [inline src/network/network_models/networks.jl]: There is some unwanted outcome of a search - replace

File: src/network/network_models/networks.jl [hunk 16]
```diff
@@ -44,7 +44,7 @@ abstract type AbstractConicPowerFormulation <: AbstractPowerFormulation end
 abstract type AbstractBFForm <: AbstractPowerFormulation end
 
 "for variants of branch flow models that target QP or NLP solvers"
-abstract type AbstractBFQPForm <: AbstractBFForm end
+abstract type AbstractBFqPForm <: AbstractBFForm end
```
Comment (jd-lara) [inline src/network/network_models/networks.jl]: here too.

File: src/network/network_models/networks.jl [hunk 17]
```diff
@@ -367,7 +367,7 @@ QCWRTriPowerModel(data::Dict{String, Any}; kwargs...) = GenericPowerModel(data,
 
 
 ""
-abstract type SOCBFForm <: AbstractBFQPForm end
+abstract type SOCBFForm <: AbstractBFqPForm end
```
Comment (jd-lara) [inline src/network/network_models/networks.jl]: and here

File: src/network/network_models/powermodels_interface.jl [hunk 18]
```diff
@@ -298,8 +298,8 @@ function PMvarmap(system_formulation::Type{S}) where {S <: PM.DCPlosslessForm}
     pm_var_map = Dict{Type,Dict{Symbol, Union{Symbol,NamedTuple}}}()
```
Comment (jd-lara) [inline src/network/network_models/powermodels_interface.jl]: Dispatch on the concrete like this `system_formulation::Type{PM.DCPlosslessForm}`

File: src/devices/device_models/AC_branches.jl (hunk 10 above)
Comment (claytonpbarrows) [reply src/devices/device_models/AC_branches.jl]: We can't populate bounds here if we want to support `StaticXXXUnbounded` since we aren't dispatching on device formulationf or the variable creation. Instead, we'll need to update the bounds in the flow/rate constraint functions.

File: src/devices/device_models/AC_branches.jl (hunk 11 above)
Comment (claytonpbarrows) [reply src/devices/device_models/AC_branches.jl]: I thought that the entire point was to dispatch on the abstract type above the concrete types so that we support user extension. Without that abstraction, users always have to use the struct `MonitoredLine` to invoke this constraint.

File: src/devices/device_models/AC_branches.jl (hunk 12 above)
Comment (claytonpbarrows) [reply src/devices/device_models/AC_branches.jl]: if `Line1` has a `flowlimits(min=-100,max=200)` we need to keep track of the directionality of the values.

File: src/devices/device_models/DC_branches.jl (hunk 13 above)
Comment (claytonpbarrows) [reply src/devices/device_models/DC_branches.jl]: this now catches the `PM.NFAForm` in [this test](https://github.com/NREL/PowerSimulations.jl/pull/188/files#diff-148cdaa0ecb52b016c6b7ed0ce62d7f4L143)

File: src/network/network_models/powermodels_interface.jl (hunk 18 above)
Comment (claytonpbarrows) [reply src/network/network_models/powermodels_interface.jl]: this isn't a concrete type
```
julia> TypeTree(PowerSimulations.PowerModels.DCPlosslessForm)
PowerModels.DCPlosslessForm
├──StandardPTDFForm
└──PowerModels.NFAForm
```

Comment (jd-lara) [reply src/network/network_models/powermodels_interface.jl]: got it

**Comment by jd-lara** [comment]
@claytonpbarrows can you resolve the conflict please.
