### PR TITLE
Fix Min-up/down time constraints in UC formulation

### LINKED ISSUE #124: support time as a function of simulation periods in duration constraints
```julia
julia> PSI.UnitCommitment(sys_rts, PSI.CopperPlatePowerModel; optimizer = xpress_optimizer, parameters = false)
┌ Warning: Initial Conditions not provided, this can lead to infeasible problem formulations
└ @ PowerSimulations ~/.julia/packages/PowerSimulations/qFdN0/src/devices/device_constructors/thermalgeneration_constructor.jl:70
[ Info: Initial status conditions not provided. This can lead to unwanted results
[ Info: Initial conditions for rate of change not provided. This can lead to unwanted results
[ Info: Initial conditions for time up/down not provided. This can lead to unwanted results
ERROR: KeyError: key 0.7999999999999998 not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] lookup_index at /Users/cbarrows/.julia/packages/JuMP/yGzKv/src/Containers/DenseAxisArray.jl:120 [inlined]
 [3] _to_index_tuple at /Users/cbarrows/.julia/packages/JuMP/yGzKv/src/Containers/DenseAxisArray.jl:129 [inlined] (repeats 2 times)
 [4] to_index at /Users/cbarrows/.julia/packages/JuMP/yGzKv/src/Containers/DenseAxisArray.jl:147 [inlined]
 [5] getindex(::JuMP.Containers.DenseAxisArray{VariableRef,2,Tuple{Array{String,1},UnitRange{Int64}},Tuple{Dict{String,Int64},Dict{Int64,Int64}}}, ::String, ::Float64) at /Users/cbarrows/.julia/packages/JuMP/yGzKv/src/Containers/DenseAxisArray.jl:161
 [6] (::getfield(PowerSimulations, Symbol("##254#258")){PowerSimulations.CanonicalModel,Tuple{Symbol,Symbol,Symbol}})(::Float64) at ./none:0
 [7] iterate at ./generator.jl:47 [inlined]
 [8] grow_to!(::Array{Any,1}, ::Base.Generator{Base.Iterators.Filter{getfield(PowerSimulations, Symbol("##255#259")),StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}},getfield(PowerSimulations, Symbol("##254#258")){PowerSimulations.CanonicalModel,Tuple{Symbol,Symbol,Symbol}}}) at ./array.jl:666
 [9] collect at ./array.jl:604 [inlined]
 [10] macro expansion at /Users/cbarrows/.julia/packages/JuMP/yGzKv/src/macros.jl:380 [inlined]
 [11] device_duration_retrospective(::PowerSimulations.CanonicalModel, ::Tuple{Array{String,1},Array{NamedTuple{(:up, :down),Tuple{Float64,Float64}},1}}, ::Array{PowerSimulations.InitialCondition,1}, ::Array{PowerSimulations.InitialCondition,1}, ::UnitRange{Int64}, ::Symbol, ::Tuple{Symbol,Symbol,Symbol}) at /Users/cbarrows/.julia/packages/PowerSimulations/qFdN0/src/devices/device_models/common/duration_constraints.jl:37
 [12] time_constraints(::PowerSimulations.CanonicalModel, ::Array{ThermalDispatch,1}, ::Type{PowerSimulations.ThermalUnitCommitment}, ::Type{CopperPlatePowerModel}, ::UnitRange{Int64}, ::Bool) at /Users/cbarrows/.julia/packages/PowerSimulations/qFdN0/src/devices/device_models/thermal_generation.jl:407
 [13] #construct_device!#104(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:parameters,),Tuple{Bool}}}, ::Function, ::PowerSimulations.CanonicalModel, ::Type{ThermalGen}, ::Type{PowerSimulations.ThermalUnitCommitment}, ::Type{CopperPlatePowerModel}, ::PowerSystem{ElectricLoad,Array{Branch,1},Array{Storage,1}}, ::UnitRange{Int64}) at /Users/cbarrows/.julia/packages/PowerSimulations/qFdN0/src/devices/device_constructors/thermalgeneration_constructor.jl:85
 [14] #construct_device! at ./none:0 [inlined]
 [15] #construct_device!#4 at /Users/cbarrows/.julia/packages/PowerSimulations/qFdN0/src/core/device_constructor.jl:8 [inlined]
 [16] (::getfield(PowerSimulations, Symbol("#kw##construct_device!")))(::NamedTuple{(:parameters,),Tuple{Bool}}, ::typeof(PowerSimulations.construct_device!), ::PowerSimulations.CanonicalModel, ::PowerSimulations.DeviceModel{ThermalGen,PowerSimulations.ThermalUnitCommitment}, ::Type{CopperPlatePowerModel}, ::PowerSystem{ElectricLoad,Array{Branch,1},Array{Storage,1}}, ::UnitRange{Int64}) at ./none:0
 [17] #build_canonical_model#8(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:parameters,),Tuple{Bool}}}, ::Function, ::Type{CopperPlatePowerModel}, ::Dict{Symbol,PowerSimulations.DeviceModel}, ::Dict{Symbol,PowerSimulations.DeviceModel}, ::Dict{Symbol,PowerSimulations.ServiceModel}, ::PowerSystem{ElectricLoad,Array{Branch,1},Array{Storage,1}}, ::OptimizerFactory) at /Users/cbarrows/.julia/packages/PowerSimulations/qFdN0/src/core/canonical_constructor.jl:101
 [18] #build_canonical_model at ./none:0 [inlined]
 [19] #PowerOperationModel#2 at /Users/cbarrows/.julia/packages/PowerSimulations/qFdN0/src/core/core_structs/operation_model.jl:24 [inlined]
 [20] Type at ./none:0 [inlined]
 [21] #UnitCommitment#161(::OptimizerFactory, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:parameters,),Tuple{Bool}}}, ::Type, ::PowerSystem{ElectricLoad,Array{Branch,1},Array{Storage,1}}, ::Type{CopperPlatePowerModel}) at /Users/cbarrows/.julia/packages/PowerSimulations/qFdN0/src/operation_models/unit_commitment.jl:11
 [22] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:optimizer, :parameters),Tuple{OptimizerFactory,Bool}}, ::Type{UnitCommitment}, ::PowerSystem{ElectricLoad,Array{Branch,1},Array{Storage,1}}, ::Type{CopperPlatePowerModel}) at ./none:0
 [23] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by sourabhdalvi**
We need to round up minimum up/down time requirement to integers.
Would prefer to have this added in PowerSystems parsing checks, rather than in constraint creation
Fixes #124

### CODE REVIEW

**Comment by jd-lara** [comment]
This is already addressed in #134. Even if the model has a fraction of hour Min-Up Down times this would be relevant for models with sub-hour resolutions. For now, it is ok and just needs to have a warning that UC models only solve for hourly resolution.

File: src/devices/device_models/common/duration_constraints.jl [hunk 1]
```diff
@@ -32,8 +32,8 @@ function device_duration_retrospective(ps_m::CanonicalModel,
                     tsd = max(1.0, duration_data[2][ix].down - initial_duration_off[ix].value)
                 end
 
-                ps_m.constraints[name_up][name, t] = JuMP.@constraint(ps_m.JuMPmodel, sum([ps_m.variables[var_names[2]][name,i] for i in ((t - tst + 1) :t) if i > 0 ]) <= ps_m.variables[var_names[1]][name,t])
-                ps_m.constraints[name_down][name, t] = JuMP.@constraint(ps_m.JuMPmodel, sum([ps_m.variables[var_names[3]][name,i] for i in ((t - tsd + 1) :t) if i > 0]) <= (1 - ps_m.variables[var_names[1]][name,t]))
+                ps_m.constraints[name_up][name, t] = JuMP.@constraint(ps_m.JuMPmodel, sum([ps_m.variables[var_names[2]][name,i] for i in ((t - round(tst) + 1) :t) if i > 0 ]) <= ps_m.variables[var_names[1]][name,t])
```
Comment (jd-lara) [inline src/devices/device_models/common/duration_constraints.jl]: This wouldn't work for models with 5-min resolution. Before adding this constraints add a warning

Comment (sourabhdalvi) [reply src/devices/device_models/common/duration_constraints.jl]: I'll definitely add a warning for now. 
But as long as time_range is defined as UnitRange, fractional requirements will not work for any model. If we continue using this format then the Min-up/down requirement (also initial_duration_on/initial_duration_off) should be in no. of periods the unit has to be online/offline (regardless if 1 period is 5min or 1hr)

Comment (jd-lara) [reply src/devices/device_models/common/duration_constraints.jl]: time_range is the number of steps in the look_ahead. We can change that name to make it more clear.

**Comment by jd-lara** [comment]
LGTM you can merge as soon as the tests pass. We will release as v0.1.1
